on:
  workflow_dispatch:
    inputs:
      ref:
        description: Equal to github.ref property
        required: true
        default: refs/head/main
      ref_name:
        description: Equal to github.ref_name property
        required: true
        default: main
      ref_type:
        description: Equal to github.ref_type property
        required: true
        default: branch

jobs:
  accepted:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
    - run: |
        echo "ref: ${{ github.event.inputs.ref }}"
        echo "ref_name: ${{ github.event.inputs.ref_name }}"
        echo "ref_type: ${{ github.event.inputs.ref_type }}"

    - name: checkout
      uses: actions/checkout@v3

    - name: clone
      run: |
        gh repo clone zzak/workflow-test-upstream -- --depth 1 --branch ${{ github.event.inputs.ref_name }}

    - name: report
      working-directory: workflow-test-upstream
      run: |
        git remote show origin

    - name: publish
      run: |
        mkdir -p ${{ github.event.inputs.ref_name }}
        cp workflow-test-upstream/docs ${{ github.event.inputs.ref_name }}

        git config --global user.name "rails-bot"
        git config --global user.email "rails-bot@users.noreply.github.com"

        git add ${{ github.event.inputs.ref_name }}
        git commit -m "${{ github.event.inputs.ref_name }}"
        git push